#!/bin/bash
commit_message=$(cat $1)
branch_name=$(git branch --show-current)
branch_message=$(echo "$branch_name" | sed -r "s/^feature\/(.*)/\1/")
issue_no=$(echo "$branch_message" | sed -r "s/(.*)(ISSUE-[0-9]+).*/\2/")
commit_message_branch=$(echo "$branch_message" | sed -r "s/^ISSUE-[0-9]+(.*)/\1/" )

if [ "${commit_message:0:1}" = "x" ] || [ "${commit_message:0:1}" = "ㅌ" ] || [ "${commit_message:0:1}" = "" ] ; then
    commit_message="$commit_message_branch"
fi

if [ "${commit_message:0:1}" != "[" ] ; then
    if [ "${branch_message}" = "${issue_no}" ] ; then
        commit_message="[NO-ISSUE] ${commit_message}"
    else
        commit_message="[${issue_no}] ${commit_message}"
    fi
fi

echo "$commit_message" > $1

exit 0
