#!/bin/bash

branch_name=$(git branch --show-current)
commit_message=$(git log -n 1 --no-merges --decorate=no --oneline | sed -r 's/([a-f0-9]+ )//')

commit_message_part1=$(echo "$commit_message" | sed -n "1p" )
commit_message_part1_issue_no=$(echo "$commit_message_part1" | sed -r "s/^\[(.*)\][ -,_.](.*)/\1/")
commit_message_part1_message=$(echo "$commit_message_part1" | sed -r "s/^\[(.*)\][ -,_.](.*)/\2/")

pull_request_message="1. ISSUE : ${commit_message_part1_issue_no}
2. 무엇을
 * ${commit_message_part1_message}
3. 어떻게
 *
4. 왜
 *
"

function urlEncode() {
    string=$1
    encoded=$(echo "$string" | perl -pe 's/([^a-zA-Z0-9_.!~*()'\''-])/sprintf("%%%02x", ord($1))/ge')
    echo "$encoded"
}

echo "https://github.com/eastar-dev/EastarLog2/compare/${branch_name//\#/%23}?quick_pull=1&labels=bug,question&assignees=easter-dev&body=$(urlEncode "${pull_request_message}")&title=$(urlEncode "${commit_message_part1}")" | pbcopy
